[project]
name = "imagecooler-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pillow>=12.0.0",
    "pyright>=1.1.407",
]

[tool.pyright]
venvPath = "."
venv = ".venv"
